/// Unique, name-related image URLs for places without owner uploads.
class PlaceImageUrls {
  PlaceImageUrls._();

  static const _version = 'v3';

  static const _autoHosts = [
    'pollinations.ai',
    'loremflickr.com',
    'picsum.photos',
  ];

  static bool isAutoGenerated(String url) {
    final lower = url.toLowerCase();
    return _autoHosts.any(lower.contains);
  }

  static String primary({
    required String name,
    required String category,
    required String seed,
    String? description,
    String? address,
  }) {
    return _imageUrl(
      name: name,
      category: category,
      seed: seed,
      variant: 0,
      description: description,
      address: address,
    );
  }

  static List<String> gallery({
    required String name,
    required String category,
    required String seed,
    String? description,
    String? address,
  }) {
    return List.generate(
      3,
      (i) => _imageUrl(
        name: name,
        category: category,
        seed: seed,
        variant: i,
        description: description,
        address: address,
      ),
    );
  }

  /// Picsum fallback — unique per place, used only when the main image fails to load.
  static String fallback({
    required String seed,
    required int variant,
  }) {
    final slug = Uri.encodeComponent('${seed}_$variant');
    return 'https://picsum.photos/seed/$slug/800/600?$_version';
  }

  static String _imageUrl({
    required String name,
    required String category,
    required String seed,
    required int variant,
    String? description,
    String? address,
  }) {
    final prompt = _buildPrompt(
      name: name,
      category: category,
      variant: variant,
      description: description,
      address: address,
    );
    final imageSeed = _imageSeed(seed, variant, prompt);
    final encodedPrompt = Uri.encodeComponent(prompt);
    return 'https://image.pollinations.ai/prompt/$encodedPrompt'
        '?width=800&height=600&seed=$imageSeed&nologo=true&$_version';
  }

  /// Stable numeric seed so the same place always gets the same image.
  static int _imageSeed(String seed, int variant, String prompt) {
    return Object.hash(seed, variant, prompt).abs() % 2147483647;
  }

  static String _buildPrompt({
    required String name,
    required String category,
    required int variant,
    String? description,
    String? address,
  }) {
    final detail = _detailText(description, address);
    final view = switch (variant) {
      0 => 'exterior street view',
      1 => 'interior inside',
      _ => 'cozy atmosphere',
    };

    final buffer = StringBuffer()
      ..write('Photo of "$name"')
      ..write(', a $category')
      ..write(', $view');
    if (detail.isNotEmpty) {
      buffer.write(', $detail');
    }
    buffer.write(', realistic travel photography, natural lighting');
    return buffer.toString();
  }

  static String _detailText(String? description, String? address) {
    final desc = (description ?? '').trim();
    final addr = (address ?? '').trim();

    if (desc.isNotEmpty && addr.isNotEmpty && desc != addr) {
      return _truncate('$desc, $addr', 120);
    }
    if (desc.isNotEmpty) return _truncate(desc, 100);
    if (addr.isNotEmpty) return _truncate(addr, 100);
    return '';
  }

  static String _truncate(String text, int maxLen) {
    if (text.length <= maxLen) return text;
    return '${text.substring(0, maxLen).trim()}…';
  }
}
