import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:geolocator/geolocator.dart';
import '../models/place.dart';
import '../models/review.dart';
import '../utils/place_image_urls.dart';
import 'user_score_service.dart';

class FirestoreService {
  final FirebaseFirestore _firestore;

  FirestoreService({FirebaseFirestore? firestore})
      : _firestore = firestore ?? FirebaseFirestore.instance;

  CollectionReference<Map<String, dynamic>> get _placesCollection =>
      _firestore.collection('places');

  Future<void> upsertPlaces(List<Place> places) async {
    if (places.isEmpty) return;

    final batch = _firestore.batch();
    for (final place in places) {
      batch.set(
        _placesCollection.doc(place.id),
        {
          'name': place.name,
          'description': place.description,
          'address': place.address,
          'category': place.category,
          'latitude': place.latitude,
          'longitude': place.longitude,
          'location': GeoPoint(place.latitude, place.longitude),
          if (place.imageUrls.any((u) => !PlaceImageUrls.isAutoGenerated(u)))
            'imageUrls': place.imageUrls
                .where((u) => !PlaceImageUrls.isAutoGenerated(u))
                .toList(),
          'tips': place.tips,
          'rating': place.rating,
          'reviewCount': place.reviewCount,
          'isOpen': place.isOpen,
          'budget': place.budget,
          'atmosphere': place.atmosphere,
          'source': 'mapbox',
          'updatedAt': FieldValue.serverTimestamp(),
        },
        SetOptions(merge: true),
      );
    }
    await batch.commit();
  }

  Future<List<Place>> fetchPlaces({String? category}) async {
    Query<Map<String, dynamic>> query = _placesCollection;
    if (category != null && category != 'All') {
      query = query.where('category', isEqualTo: category);
    }
    final snapshot = await query.get();
    final places = snapshot.docs.map(Place.fromDoc).toList();
    places.sort((a, b) => b.rating.compareTo(a.rating));
    return places;
  }

  Future<List<Place>> fetchSponsoredPlaces({int limit = 5}) async {
    try {
      final snapshot = await _placesCollection
          .where('isSponsored', isEqualTo: true)
          .limit(limit)
          .get();
      return snapshot.docs.map(Place.fromDoc).toList();
    } catch (_) {
      final all = await fetchPlaces();
      return all.take(limit).toList();
    }
  }

  Future<int> getPinnedPlaceCount(String userId) async {
    final snapshot = await _firestore
        .collection('users')
        .doc(userId)
        .collection('pins')
        .get();
    return snapshot.docs.length;
  }

  Future<void> setUserPremium({
    required String userId,
    required bool isPremium,
  }) async {
    await _firestore.collection('users').doc(userId).update({
      'isPremium': isPremium,
      'isSuperUser': isPremium,
      'pinLimit': isPremium ? 999 : 5,
    });
  }

  Future<void> updateUserPreferences({
    required String userId,
    required Map<String, dynamic> preferences,
  }) async {
    await _firestore.collection('users').doc(userId).set(
      {'preferences': preferences},
      SetOptions(merge: true),
    );
  }

  Future<Map<String, dynamic>> getUserPreferences(String userId) async {
    final doc = await _firestore.collection('users').doc(userId).get();
    final prefs = doc.data()?['preferences'];
    if (prefs is Map<String, dynamic>) return prefs;
    return {};
  }

  Future<List<Place>> fetchNearbyPlaces({
    required double userLatitude,
    required double userLongitude,
    double radiusKm = 20,
    String? category,
  }) async {
    final places = await fetchPlaces(category: category);
    return places
        .map(
          (place) => place.copyWith(
            distanceKm: Geolocator.distanceBetween(
                  userLatitude,
                  userLongitude,
                  place.latitude,
                  place.longitude,
                ) /
                1000,
          ),
        )
        .where((place) => (place.distanceKm ?? double.infinity) <= radiusKm)
        .toList()
      ..sort((a, b) => (a.distanceKm ?? 0).compareTo(b.distanceKm ?? 0));
  }

  Future<Place?> getPlaceById(String placeId) async {
    final doc = await _placesCollection.doc(placeId).get();
    if (!doc.exists) return null;
    return Place.fromDoc(doc);
  }

  Stream<List<Review>> streamPlaceReviews(String placeId) {
    return _placesCollection
        .doc(placeId)
        .collection('reviews')
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map(
          (snapshot) => snapshot.docs
              .map((doc) => Review.fromDoc(doc, placeId: placeId))
              .toList(),
        );
  }

  Future<bool> isPlacePinned({
    required String userId,
    required String placeId,
  }) async {
    final pinDoc = await _firestore
        .collection('users')
        .doc(userId)
        .collection('pins')
        .doc(placeId)
        .get();
    return pinDoc.exists;
  }

  Future<void> togglePinPlace({
    required String userId,
    required Place place,
  }) async {
    final pinRef = _firestore
        .collection('users')
        .doc(userId)
        .collection('pins')
        .doc(place.id);

    final pinSnapshot = await pinRef.get();
    if (pinSnapshot.exists) {
      await pinRef.delete();
      return;
    }

    final userDoc = await _firestore.collection('users').doc(userId).get();
    final userData = userDoc.data() ?? {};
    final isPremium = userData['isPremium'] as bool? ?? false;
    final pinLimit = (userData['pinLimit'] as num?)?.toInt() ?? 5;
    if (!isPremium) {
      final count = await getPinnedPlaceCount(userId);
      if (count >= pinLimit) {
        throw PinLimitReachedException(pinLimit);
      }
    }

    await pinRef.set({
      'placeId': place.id,
      'name': place.name,
      'category': place.category,
      'address': place.address,
      'latitude': place.latitude,
      'longitude': place.longitude,
      'budget': place.budget,
      'atmosphere': place.atmosphere,
      'imageUrl': place.primaryImageUrl,
      'rating': place.rating,
      'createdAt': FieldValue.serverTimestamp(),
    });
  }

  Stream<List<Place>> streamPinnedPlaces(String userId) {
    return _firestore
        .collection('users')
        .doc(userId)
        .collection('pins')
        .snapshots()
        .map((snapshot) {
      return snapshot.docs.map((doc) {
        final data = doc.data();
        final lat = (data['latitude'] as num?)?.toDouble() ?? 0;
        final lng = (data['longitude'] as num?)?.toDouble() ?? 0;
        final name = (data['name'] as String?) ?? 'Pinned place';
        final category = (data['category'] as String?) ?? 'Other';
        final address = (data['address'] as String?) ?? '';
        final rawImageUrl = (data['imageUrl'] as String?)?.trim();
        final imageUrl = rawImageUrl != null && rawImageUrl.isNotEmpty
            ? rawImageUrl
            : Place.generatedImageUrl(
                name: name,
                category: category,
                description: address,
                address: address,
                seed: (data['placeId'] as String?) ?? doc.id,
              );
        return Place(
          id: (data['placeId'] as String?) ?? doc.id,
          name: name,
          description: address,
          address: address,
          category: category,
          latitude: lat,
          longitude: lng,
          mediaUrls: [imageUrl],
          mediaTypes: ['image'],
          tips: const [],
          rating: (data['rating'] as num?)?.toDouble() ?? 0,
          reviewCount: 0,
          isOpen: true,
          budget: (data['budget'] as String?) ?? 'medium',
          atmosphere: (data['atmosphere'] as String?) ?? 'lively',
        );
      }).where((p) => p.latitude != 0 || p.longitude != 0).toList();
    });
  }

  Future<void> addReview({
    required String placeId,
    required String userId,
    required String userName,
    required String comment,
    required int rating,
  }) async {
    final docRef = _placesCollection.doc(placeId).collection('reviews').doc();
    await docRef.set({
      'userId': userId,
      'userName': userName,
      'comment': comment,
      'rating': rating,
      'createdAt': FieldValue.serverTimestamp(),
    });

    await _updatePlaceRatingStats(placeId);

    final userRef = _firestore.collection('users').doc(userId);
    await _firestore.runTransaction((transaction) async {
      final userSnapshot = await transaction.get(userRef);
      if (userSnapshot.exists) {
        final currentReviews =
            (userSnapshot.data()?['reviewsCount'] as num?)?.toInt() ?? 0;
        transaction.update(userRef, {'reviewsCount': currentReviews + 1});
      }
    });
    await UserScoreService().updateUserScore(userId);
  }

  Future<void> editReview({
    required String placeId,
    required String reviewId,
    required String userId,
    required String comment,
    required int rating,
  }) async {
    await _placesCollection
        .doc(placeId)
        .collection('reviews')
        .doc(reviewId)
        .update({
      'comment': comment,
      'rating': rating,
      'updatedAt': FieldValue.serverTimestamp(),
    });

    await _updatePlaceRatingStats(placeId);
    await UserScoreService().updateUserScore(userId);
  }

  Future<void> deleteReview({
    required String placeId,
    required String reviewId,
    required String userId,
  }) async {
    await _placesCollection
        .doc(placeId)
        .collection('reviews')
        .doc(reviewId)
        .delete();

    await _updatePlaceRatingStats(placeId);

    final userRef = _firestore.collection('users').doc(userId);
    await _firestore.runTransaction((transaction) async {
      final userSnapshot = await transaction.get(userRef);
      if (userSnapshot.exists) {
        final currentReviews =
            (userSnapshot.data()?['reviewsCount'] as num?)?.toInt() ?? 0;
        transaction.update(userRef, {
          'reviewsCount': currentReviews > 0 ? currentReviews - 1 : 0,
        });
      }
    });
    await UserScoreService().updateUserScore(userId);
  }

  Future<void> _updatePlaceRatingStats(String placeId) async {
    final reviewsSnapshot =
        await _placesCollection.doc(placeId).collection('reviews').get();

    final reviews = reviewsSnapshot.docs;
    if (reviews.isEmpty) {
      await _placesCollection.doc(placeId).update({
        'rating': 0.0,
        'reviewCount': 0,
      });
      return;
    }

    final totalRating = reviews.fold<int>(0, (acc, doc) {
      final rating = (doc.data()['rating'] as num?)?.toInt() ?? 0;
      return acc + rating;
    });

    final avgRating = totalRating / reviews.length;

    await _placesCollection.doc(placeId).update({
      'rating': avgRating,
      'reviewCount': reviews.length,
    });
  }

  Future<Set<String>> fetchSuperUserIds() async {
    try {
      final snapshot = await _firestore
          .collection('users')
          .where('isSuperUser', isEqualTo: true)
          .get();
      return snapshot.docs.map((doc) => doc.id).toSet();
    } catch (_) {
      return {};
    }
  }
}

class PinLimitReachedException implements Exception {
  final int limit;
  PinLimitReachedException(this.limit);

  @override
  String toString() => 'Pin limit reached ($limit). Upgrade to Premium for unlimited pins.';
}
