import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:geolocator/geolocator.dart';
import '../models/place.dart';
import '../models/review.dart';
import '../utils/place_image_urls.dart';

class FirestoreService {
  final FirebaseFirestore _firestore;

  FirestoreService({FirebaseFirestore? firestore})
      : _firestore = firestore ?? FirebaseFirestore.instance;

  CollectionReference<Map<String, dynamic>> get _placesCollection =>
      _firestore.collection('places');

  Future<void> upsertPlaces(List<Place> places) async {
    if (places.isEmpty) return;

    final batch = _firestore.batch();
    for (final place in places) {
      batch.set(
        _placesCollection.doc(place.id),
        {
          'name': place.name,
          'description': place.description,
          'address': place.address,
          'category': place.category,
          'latitude': place.latitude,
          'longitude': place.longitude,
          'location': GeoPoint(place.latitude, place.longitude),
          if (place.imageUrls.any((u) => !PlaceImageUrls.isAutoGenerated(u)))
            'imageUrls': place.imageUrls
                .where((u) => !PlaceImageUrls.isAutoGenerated(u))
                .toList(),
          'tips': place.tips,
          'rating': place.rating,
          'reviewCount': place.reviewCount,
          'isOpen': place.isOpen,
          'budget': place.budget,
          'atmosphere': place.atmosphere,
          'source': 'mapbox',
          'updatedAt': FieldValue.serverTimestamp(),
        },
        SetOptions(merge: true),
      );
    }
    await batch.commit();
  }

  Future<List<Place>> fetchPlaces({String? category}) async {
    Query<Map<String, dynamic>> query = _placesCollection;
    if (category != null && category != 'All') {
      query = query.where('category', isEqualTo: category);
    }
    final snapshot = await query.get();
    final places = snapshot.docs.map(Place.fromDoc).toList();
    places.sort((a, b) => b.rating.compareTo(a.rating));
    return places;
  }

  Future<List<Place>> fetchNearbyPlaces({
    required double userLatitude,
    required double userLongitude,
    double radiusKm = 20,
    String? category,
  }) async {
    final places = await fetchPlaces(category: category);
    return places
        .map(
          (place) => place.copyWith(
            distanceKm: Geolocator.distanceBetween(
                  userLatitude,
                  userLongitude,
                  place.latitude,
                  place.longitude,
                ) /
                1000,
          ),
        )
        .where((place) => (place.distanceKm ?? double.infinity) <= radiusKm)
        .toList()
      ..sort((a, b) => (a.distanceKm ?? 0).compareTo(b.distanceKm ?? 0));
  }

  Future<Place?> getPlaceById(String placeId) async {
    final doc = await _placesCollection.doc(placeId).get();
    if (!doc.exists) return null;
    return Place.fromDoc(doc);
  }

  Stream<List<Review>> streamPlaceReviews(String placeId) {
    return _placesCollection
        .doc(placeId)
        .collection('reviews')
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map(
          (snapshot) => snapshot.docs
              .map((doc) => Review.fromDoc(doc, placeId: placeId))
              .toList(),
        );
  }

  Future<bool> isPlacePinned({
    required String userId,
    required String placeId,
  }) async {
    final pinDoc = await _firestore
        .collection('users')
        .doc(userId)
        .collection('pins')
        .doc(placeId)
        .get();
    return pinDoc.exists;
  }

  Future<void> togglePinPlace({
    required String userId,
    required Place place,
  }) async {
    final pinRef = _firestore
        .collection('users')
        .doc(userId)
        .collection('pins')
        .doc(place.id);

    final pinSnapshot = await pinRef.get();
    if (pinSnapshot.exists) {
      await pinRef.delete();
      return;
    }

    await pinRef.set({
      'placeId': place.id,
      'name': place.name,
      'category': place.category,
      'address': place.address,
      'latitude': place.latitude,
      'longitude': place.longitude,
      'budget': place.budget,
      'atmosphere': place.atmosphere,
      'imageUrl': place.primaryImageUrl,
      'rating': place.rating,
      'createdAt': FieldValue.serverTimestamp(),
    });
  }

  Stream<List<Place>> streamPinnedPlaces(String userId) {
    return _firestore
        .collection('users')
        .doc(userId)
        .collection('pins')
        .snapshots()
        .map((snapshot) {
      return snapshot.docs.map((doc) {
        final data = doc.data();
        final lat = (data['latitude'] as num?)?.toDouble() ?? 0;
        final lng = (data['longitude'] as num?)?.toDouble() ?? 0;
        final name = (data['name'] as String?) ?? 'Pinned place';
        final category = (data['category'] as String?) ?? 'Other';
        final address = (data['address'] as String?) ?? '';
        final rawImageUrl = (data['imageUrl'] as String?)?.trim();
        final imageUrl = rawImageUrl != null && rawImageUrl.isNotEmpty
            ? rawImageUrl
            : Place.generatedImageUrl(
                name: name,
                category: category,
                description: address,
                address: address,
                seed: (data['placeId'] as String?) ?? doc.id,
              );
        return Place(
          id: (data['placeId'] as String?) ?? doc.id,
          name: name,
          description: address,
          address: address,
          category: category,
          latitude: lat,
          longitude: lng,
          imageUrls: [imageUrl],
          tips: const [],
          rating: (data['rating'] as num?)?.toDouble() ?? 0,
          reviewCount: 0,
          isOpen: true,
          budget: (data['budget'] as String?) ?? 'medium',
          atmosphere: (data['atmosphere'] as String?) ?? 'lively',
        );
      }).where((p) => p.latitude != 0 || p.longitude != 0).toList();
    });
  }
}
