import 'package:cloud_firestore/cloud_firestore.dart';
import '../utils/place_image_urls.dart';

class Place {
  final String id;
  final String ownerId;
  final String ownerName;
  final String name;
  final String description;
  final String category;
  final String address;
  final double latitude;
  final double longitude;
  final List<String> tips;
  final double rating;
  final int reviewCount;
  final bool isOpen;
  final String budget;
  final String atmosphere;
  final double? distanceKm;
  final String localTips;
  final String recommendedDishes;
  final List<String> mediaUrls;
  final List<String> mediaTypes;
  final bool isSponsored;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  const Place({
    required this.id,
    this.ownerId = '',
    this.ownerName = '',
    required this.name,
    required this.description,
    required this.category,
    required this.address,
    required this.latitude,
    required this.longitude,
    this.tips = const [],
    this.rating = 0.0,
    this.reviewCount = 0,
    this.isOpen = true,
    this.budget = 'medium',
    this.atmosphere = 'lively',
    this.distanceKm,
    this.localTips = '',
    this.recommendedDishes = '',
    this.mediaUrls = const [],
    this.mediaTypes = const [],
    this.isSponsored = false,
    this.createdAt,
    this.updatedAt,
  });

  static String generatedImageUrl({
    required String name,
    required String category,
    String? description,
    String? address,
    String? seed,
  }) {
    return PlaceImageUrls.primary(
      name: name,
      category: category,
      description: description,
      address: address,
      seed: seed ?? name,
    );
  }

  String get _imageContextDescription {
    if (description.trim().isNotEmpty) return description;
    if (address.trim().isNotEmpty) return address;
    return category;
  }

  List<String> get imageUrls {
    final images = <String>[];
    if (mediaUrls.isEmpty) return images;
    for (var i = 0; i < mediaUrls.length; i++) {
      final type = i < mediaTypes.length ? mediaTypes[i] : 'image';
      if (type == 'image') {
        images.add(mediaUrls[i]);
      }
    }
    return images;
  }

  List<({String url, String type})> get displayMedia {
    final custom = <({String url, String type})>[];
    for (var i = 0; i < mediaUrls.length; i++) {
      if (!PlaceImageUrls.isAutoGenerated(mediaUrls[i])) {
        final type = i < mediaTypes.length ? mediaTypes[i] : 'image';
        custom.add((url: mediaUrls[i], type: type));
      }
    }
    if (custom.isNotEmpty) return custom;

    return PlaceImageUrls.gallery(
      name: name,
      category: category,
      seed: id,
      description: _imageContextDescription,
      address: address,
    ).map((url) => (url: url, type: 'image')).toList();
  }

  /// Owner-uploaded photos when present; otherwise unique AI photos per place.
  List<String> get displayImageUrls {
    final custom =
        imageUrls.where((url) => !PlaceImageUrls.isAutoGenerated(url)).toList();
    if (custom.isNotEmpty) return custom;
    return PlaceImageUrls.gallery(
      name: name,
      category: category,
      seed: id,
      description: _imageContextDescription,
      address: address,
    );
  }

  String get primaryImageUrl => displayImageUrls.first;

  factory Place.fromMapboxFeature(
    Map<String, dynamic> feature,
    String category,
  ) {
    final props = feature['properties'] as Map<String, dynamic>? ?? {};
    final geometry = feature['geometry'] as Map<String, dynamic>? ?? {};
    final coordinates = geometry['coordinates'] as List<dynamic>? ?? [0, 0];
    final lng = (coordinates.first as num).toDouble();
    final lat = (coordinates.last as num).toDouble();
    final mapboxId = props['mapbox_id'] as String? ?? feature['id']?.toString();

    final name = (props['name_preferred'] as String?) ??
        (props['name'] as String?) ??
        'Unnamed place';
    final address = (props['full_address'] as String?) ??
        (props['place_formatted'] as String?) ??
        (props['address'] as String?) ??
        '';

    final traits = _mapboxTraits(category, mapboxId ?? '$lat,$lng');

    return Place(
      id: 'mapbox_${mapboxId ?? '$lat,$lng'}',
      name: name,
      description: address,
      address: address,
      category: category,
      latitude: lat,
      longitude: lng,
      mediaUrls: const [],
      mediaTypes: const [],
      tips: const [],
      rating: 4.0,
      reviewCount: 0,
      isOpen: true,
      budget: traits.$1,
      atmosphere: traits.$2,
    );
  }

  static (String, String) _mapboxTraits(String category, String seed) {
    final h = seed.hashCode.abs();
    switch (category) {
      case 'Cafés':
        return (
          ['low', 'medium', 'high'][h % 3],
          ['quiet', 'lively', 'romantic'][h % 3],
        );
      case 'Restaurants':
        return (
          ['medium', 'high', 'low'][h % 3],
          ['lively', 'romantic', 'quiet'][h % 3],
        );
      case 'Parks':
        return ('low', 'quiet');
      case 'Museums':
        return ('medium', 'quiet');
      default:
        return (
          ['low', 'medium', 'high'][h % 3],
          ['quiet', 'lively', 'romantic'][h % 3],
        );
    }
  }

  factory Place.fromFirestore(
    DocumentSnapshot<Map<String, dynamic>> snapshot,
  ) {
    return Place.fromMap(snapshot.data() ?? <String, dynamic>{}, snapshot.id);
  }

  factory Place.fromDoc(DocumentSnapshot<Map<String, dynamic>> doc) {
    return Place.fromMap(doc.data() ?? <String, dynamic>{}, doc.id);
  }

  factory Place.fromMap(Map<String, dynamic> map, [String? documentId]) {
    DateTime? readDate(dynamic value) {
      if (value is Timestamp) return value.toDate();
      if (value is DateTime) return value;
      return null;
    }

    double? readDouble(dynamic value) {
      if (value == null) return null;
      if (value is num) return value.toDouble();
      return double.tryParse(value.toString());
    }

    final geoPoint = map['location'] as GeoPoint?;
    final latitude = readDouble(map['latitude']) ?? geoPoint?.latitude ?? 0.0;
    final longitude = readDouble(map['longitude']) ?? geoPoint?.longitude ?? 0.0;

    final placeName = (map['name'] as String?)?.trim();
    final name =
        placeName != null && placeName.isNotEmpty ? placeName : 'Unnamed place';

    // Support both imageUrls (legacy) and mediaUrls (new)
    final rawMediaUrls = List<String>.from(map['mediaUrls'] ?? map['imageUrls'] ?? []);
    final customMediaUrls =
        rawMediaUrls.where((url) => !PlaceImageUrls.isAutoGenerated(url)).toList();

    return Place(
      id: documentId ?? map['id'] ?? '',
      ownerId: map['ownerId'] ?? '',
      ownerName: map['ownerName'] ?? '',
      name: name,
      description: map['description'] ?? '',
      category: map['category'] ?? 'Other',
      address: map['address'] ?? '',
      latitude: latitude,
      longitude: longitude,
      tips: (map['tips'] as List<dynamic>? ?? const [])
          .map((e) => e.toString())
          .where((e) => e.isNotEmpty)
          .toList(),
      localTips: map['localTips'] ?? '',
      recommendedDishes: map['recommendedDishes'] ?? '',
      mediaUrls: customMediaUrls,
      mediaTypes: List<String>.from(map['mediaTypes'] ?? []),
      isSponsored: map['isSponsored'] as bool? ?? false,
      rating: readDouble(map['rating']) ?? 0.0,
      reviewCount: (map['reviewCount'] as num?)?.toInt() ?? 0,
      isOpen: (map['isOpen'] as bool?) ??
          ((map['status'] as String?)?.toLowerCase() == 'open'),
      budget: ((map['budget'] as String?) ?? 'medium').toLowerCase(),
      atmosphere: ((map['atmosphere'] as String?) ?? 'lively').toLowerCase(),
      createdAt: readDate(map['createdAt']),
      updatedAt: readDate(map['updatedAt']),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'ownerId': ownerId,
      'ownerName': ownerName,
      'name': name,
      'description': description,
      'category': category,
      'address': address,
      'latitude': latitude,
      'longitude': longitude,
      'tips': tips,
      'localTips': localTips,
      'recommendedDishes': recommendedDishes,
      'mediaUrls': mediaUrls,
      'mediaTypes': mediaTypes,
      'isSponsored': isSponsored,
      'rating': rating,
      'reviewCount': reviewCount,
      'isOpen': isOpen,
      'budget': budget,
      'atmosphere': atmosphere,
      'createdAt': createdAt != null ? Timestamp.fromDate(createdAt!) : null,
      'updatedAt': updatedAt != null ? Timestamp.fromDate(updatedAt!) : null,
    };
  }

  Place copyWith({
    String? id,
    String? ownerId,
    String? ownerName,
    String? name,
    String? description,
    String? category,
    String? address,
    double? latitude,
    double? longitude,
    List<String>? tips,
    String? localTips,
    String? recommendedDishes,
    List<String>? mediaUrls,
    List<String>? mediaTypes,
    bool? isSponsored,
    double? rating,
    int? reviewCount,
    bool? isOpen,
    String? budget,
    String? atmosphere,
    double? distanceKm,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Place(
      id: id ?? this.id,
      ownerId: ownerId ?? this.ownerId,
      ownerName: ownerName ?? this.ownerName,
      name: name ?? this.name,
      description: description ?? this.description,
      category: category ?? this.category,
      address: address ?? this.address,
      latitude: latitude ?? this.latitude,
      longitude: longitude ?? this.longitude,
      tips: tips ?? this.tips,
      localTips: localTips ?? this.localTips,
      recommendedDishes: recommendedDishes ?? this.recommendedDishes,
      mediaUrls: mediaUrls ?? this.mediaUrls,
      mediaTypes: mediaTypes ?? this.mediaTypes,
      isSponsored: isSponsored ?? this.isSponsored,
      rating: rating ?? this.rating,
      reviewCount: reviewCount ?? this.reviewCount,
      isOpen: isOpen ?? this.isOpen,
      budget: budget ?? this.budget,
      atmosphere: atmosphere ?? this.atmosphere,
      distanceKm: distanceKm ?? this.distanceKm,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}
